quarkus.http.port=8080
quarkus.http.host=0.0.0.0
quarkus.datasource.db-kind=mysql
quarkus.datasource.devservices.enabled=false
quarkus.datasource.username=casadocodigo
quarkus.datasource.password=casadocodigo
quarkus.datasource.jdbc.url=jdbc:mysql://mysql:3306/casadocodigo
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=no-file
quarkus.hibernate-orm.schema-management.database.action=drop-and-create
